/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import com.controller.ControllerDB;
import com.models.Produk;
import com.models.Riwayat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author MSI BRAVO
 */
public class App extends javax.swing.JFrame {
    public void clear() {
        namaTF.setText("");
        hargaTF.setText("");
        stokTF.setText("");
        namaTF.requestFocus();
    }
    
    public void insertDataProduk(String nama, String harga, String jumlah) {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int row = jTable1.getRowCount();
        model.addRow(new Object[] {
            row += 1,
            nama,
            harga,
            jumlah
        });
    }
    
    public void insertDataRiwayat(String timestamp, String produk, String jumlah, String harga_dibeli, String uang_tunai, String uang_kembali) {
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        model.addRow(new Object[] {
            timestamp,
            produk,
            jumlah,
            harga_dibeli,
            uang_tunai,
            uang_kembali
        });
    }
    
    // private void deleteData() {
    //     DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    //     int rowSelected = jTable1.getSelectedRow();
        
    //     if (rowSelected >= 0) {
    //         int confirm = JOptionPane.showConfirmDialog(this, "Anda yakin ingin menghapus baris ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
    //         if (confirm == JOptionPane.YES_OPTION) {
    //             model.removeRow(rowSelected);
    //         }
    //     } else {
    //         JOptionPane.showMessageDialog(this, "Tidak ada baris yang dipilih.", "Peringatan", JOptionPane.WARNING_MESSAGE);
    //     }
    // }
    
    private void updateTotalHarga(String produk, String harga) {
        try {
            produkTF.setText(produk);
            Long longHarga = Long.valueOf(harga);
            int intJumlah = Integer.parseInt(jumlahTF.getText());
            totalTF.setText(String.format("Rp. %d", longHarga * intJumlah));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void updateTableProduk() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        for (Produk i : ControllerDB.getDBProduk()){
            insertDataProduk(i.getName(), String.valueOf(i.getPrice()), String.valueOf(i.getStock()));
        }
    }
    
    public void updateTableRiwayat() {
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        model.setRowCount(0);
        for (Riwayat i : ControllerDB.getDBPRiwayat()){
            insertDataRiwayat(i.getTimestamp(), i.getProduk(), String.valueOf(i.getJumlah()), String.valueOf(i.getHarga_dibeli()), String.valueOf(i.getUang_tunai()), String.valueOf(i.getUang_kembali()));
        }
    }
    
    public String selectName(){
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int rowSelected = jTable1.getSelectedRow();
        
        String valueNama = (String) model.getValueAt(rowSelected, 1);
        return valueNama;
    }
            
    // jTable1
    /**
     * Creates new form App
     */
    public App() {
        initComponents();
        updateTableProduk();
        updateTableRiwayat();
        tunaiTF.setText("Rp. ");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jpanel10 = new javax.swing.JPanel();
        totalLB = new javax.swing.JLabel();
        tunaiLB = new javax.swing.JLabel();
        kembaliLB = new javax.swing.JLabel();
        kembaliTF = new javax.swing.JTextField();
        hitungBT = new javax.swing.JButton();
        simpanBT = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        produkTF = new javax.swing.JTextField();
        jumlahTF = new javax.swing.JTextField();
        JumlahLB = new javax.swing.JLabel();
        produkLB = new javax.swing.JLabel();
        totalTF = new javax.swing.JTextField();
        tunaiTF = new javax.swing.JTextField();
        bersihkanBT = new javax.swing.JButton();
        beliBUT = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        namaLB = new javax.swing.JLabel();
        namaTF = new javax.swing.JTextField();
        hargaTF = new javax.swing.JTextField();
        stokTF = new javax.swing.JTextField();
        hargaLB = new javax.swing.JLabel();
        stokLB = new javax.swing.JLabel();
        tambahBT = new javax.swing.JButton();
        editBT = new javax.swing.JButton();
        deleteBT = new javax.swing.JButton();
        clearBT = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        riwayatLB = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(244, 80, 80));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("AF STORE TOKO SERBA ADA");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(219, 219, 219)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(244, 80, 80));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(60, 72, 107));

        jLabel5.setBackground(new java.awt.Color(153, 153, 153));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("Tabel Barang");

        jTable1.setBackground(new java.awt.Color(244, 80, 80));
        jTable1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTable1.setForeground(new java.awt.Color(240, 240, 240));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Nama", "Harga", "Stok"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Long.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(240, 240, 240));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(198, 198, 198))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                .addContainerGap())
        );

        jpanel10.setBackground(new java.awt.Color(60, 72, 107));

        totalLB.setBackground(new java.awt.Color(153, 153, 153));
        totalLB.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        totalLB.setForeground(new java.awt.Color(240, 240, 240));
        totalLB.setText("Total");

        tunaiLB.setBackground(new java.awt.Color(153, 153, 153));
        tunaiLB.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tunaiLB.setForeground(new java.awt.Color(240, 240, 240));
        tunaiLB.setText("Tunai");

        kembaliLB.setBackground(new java.awt.Color(153, 153, 153));
        kembaliLB.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        kembaliLB.setForeground(new java.awt.Color(240, 240, 240));
        kembaliLB.setText("Kembali");

        kembaliTF.setBackground(new java.awt.Color(240, 240, 240));
        kembaliTF.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        kembaliTF.setForeground(new java.awt.Color(244, 80, 80));

        hitungBT.setBackground(new java.awt.Color(249, 217, 73));
        hitungBT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        hitungBT.setForeground(new java.awt.Color(244, 80, 80));
        hitungBT.setText("Hitung");
        hitungBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungBTActionPerformed(evt);
            }
        });

        simpanBT.setBackground(new java.awt.Color(249, 217, 73));
        simpanBT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        simpanBT.setForeground(new java.awt.Color(244, 80, 80));
        simpanBT.setText("Simpan");
        simpanBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanBTActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("KASIR");
        jLabel3.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                jLabel3ComponentMoved(evt);
            }
        });

        produkTF.setBackground(new java.awt.Color(240, 240, 240));
        produkTF.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        produkTF.setForeground(new java.awt.Color(244, 80, 80));
        produkTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                produkTFActionPerformed(evt);
            }
        });

        jumlahTF.setBackground(new java.awt.Color(240, 240, 240));
        jumlahTF.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jumlahTF.setForeground(new java.awt.Color(244, 80, 80));
        jumlahTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlahTFActionPerformed(evt);
            }
        });

        JumlahLB.setBackground(new java.awt.Color(153, 153, 153));
        JumlahLB.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        JumlahLB.setForeground(new java.awt.Color(240, 240, 240));
        JumlahLB.setText("Jumlah");

        produkLB.setBackground(new java.awt.Color(153, 153, 153));
        produkLB.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        produkLB.setForeground(new java.awt.Color(240, 240, 240));
        produkLB.setText("Produk");

        totalTF.setBackground(new java.awt.Color(240, 240, 240));
        totalTF.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        totalTF.setForeground(new java.awt.Color(244, 80, 80));
        totalTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalTFActionPerformed(evt);
            }
        });

        tunaiTF.setBackground(new java.awt.Color(240, 240, 240));
        tunaiTF.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tunaiTF.setForeground(new java.awt.Color(244, 80, 80));
        tunaiTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tunaiTFActionPerformed(evt);
            }
        });

        bersihkanBT.setBackground(new java.awt.Color(249, 217, 73));
        bersihkanBT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bersihkanBT.setForeground(new java.awt.Color(244, 80, 80));
        bersihkanBT.setText("Clear");
        bersihkanBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bersihkanBTActionPerformed(evt);
            }
        });

        beliBUT.setBackground(new java.awt.Color(249, 217, 73));
        beliBUT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        beliBUT.setForeground(new java.awt.Color(244, 80, 80));
        beliBUT.setText("Beli");
        beliBUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beliBUTActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("Note : Masukkan Jumlah Barang Terlebih Dahulu");

        javax.swing.GroupLayout jpanel10Layout = new javax.swing.GroupLayout(jpanel10);
        jpanel10.setLayout(jpanel10Layout);
        jpanel10Layout.setHorizontalGroup(
            jpanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel10Layout.createSequentialGroup()
                .addGroup(jpanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanel10Layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jLabel3))
                    .addGroup(jpanel10Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpanel10Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jpanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jpanel10Layout.createSequentialGroup()
                                    .addComponent(kembaliLB)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(kembaliTF, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jpanel10Layout.createSequentialGroup()
                                        .addComponent(totalLB, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(totalTF, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jpanel10Layout.createSequentialGroup()
                                            .addComponent(tunaiLB, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(tunaiTF, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jpanel10Layout.createSequentialGroup()
                                                .addComponent(JumlahLB, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jumlahTF, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jpanel10Layout.createSequentialGroup()
                                                .addComponent(produkLB, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(produkTF, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGroup(jpanel10Layout.createSequentialGroup()
                                .addComponent(hitungBT)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(beliBUT)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(simpanBT, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bersihkanBT)))))
                .addGap(33, 33, 33))
        );
        jpanel10Layout.setVerticalGroup(
            jpanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel10Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabel4)
                .addGap(3, 3, 3)
                .addGroup(jpanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(produkLB)
                    .addComponent(produkTF, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jpanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JumlahLB)
                    .addComponent(jumlahTF, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tunaiLB)
                    .addComponent(tunaiTF, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalLB)
                    .addComponent(totalTF, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kembaliLB)
                    .addComponent(kembaliTF, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jpanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hitungBT)
                    .addComponent(beliBUT)
                    .addComponent(simpanBT)
                    .addComponent(bersihkanBT))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(60, 72, 107));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("DATA PRODUCT CONTROL");
        jLabel2.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                jLabel2ComponentMoved(evt);
            }
        });

        namaLB.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        namaLB.setForeground(new java.awt.Color(240, 240, 240));
        namaLB.setText("Nama");

        namaTF.setBackground(new java.awt.Color(240, 240, 240));
        namaTF.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        namaTF.setForeground(new java.awt.Color(244, 80, 80));
        namaTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaTFActionPerformed(evt);
            }
        });

        hargaTF.setBackground(new java.awt.Color(240, 240, 240));
        hargaTF.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        hargaTF.setForeground(new java.awt.Color(244, 80, 80));

        stokTF.setBackground(new java.awt.Color(240, 240, 240));
        stokTF.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        stokTF.setForeground(new java.awt.Color(244, 80, 80));
        stokTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stokTFActionPerformed(evt);
            }
        });

        hargaLB.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        hargaLB.setForeground(new java.awt.Color(240, 240, 240));
        hargaLB.setText("Harga");

        stokLB.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        stokLB.setForeground(new java.awt.Color(240, 240, 240));
        stokLB.setText("Stok");

        tambahBT.setBackground(new java.awt.Color(249, 217, 73));
        tambahBT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tambahBT.setForeground(new java.awt.Color(244, 80, 80));
        tambahBT.setText("Tambah");
        tambahBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahBTActionPerformed(evt);
            }
        });

        editBT.setBackground(new java.awt.Color(249, 217, 73));
        editBT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        editBT.setForeground(new java.awt.Color(244, 80, 80));
        editBT.setText("Edit");
        editBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBTActionPerformed(evt);
            }
        });

        deleteBT.setBackground(new java.awt.Color(249, 217, 73));
        deleteBT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        deleteBT.setForeground(new java.awt.Color(244, 80, 80));
        deleteBT.setText("Delete");
        deleteBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBTActionPerformed(evt);
            }
        });

        clearBT.setBackground(new java.awt.Color(249, 217, 73));
        clearBT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        clearBT.setForeground(new java.awt.Color(244, 80, 80));
        clearBT.setText("Clear");
        clearBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(34, 34, 34)
                            .addComponent(jLabel2))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(namaLB, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(stokTF)
                                .addComponent(hargaTF)
                                .addComponent(namaTF))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hargaLB, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stokLB, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(tambahBT)
                                .addGap(18, 18, 18)
                                .addComponent(editBT)
                                .addGap(18, 18, 18)
                                .addComponent(deleteBT)
                                .addGap(12, 12, 12)
                                .addComponent(clearBT)))))
                .addGap(10, 10, 10))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaLB)
                    .addComponent(namaTF, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hargaLB)
                    .addComponent(hargaTF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stokLB)
                    .addComponent(stokTF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tambahBT)
                    .addComponent(editBT)
                    .addComponent(deleteBT)
                    .addComponent(clearBT))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(60, 72, 107));

        riwayatLB.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        riwayatLB.setForeground(new java.awt.Color(240, 240, 240));
        riwayatLB.setText("Riwayat Transaksi");

        jTable2.setBackground(new java.awt.Color(244, 80, 80));
        jTable2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTable2.setForeground(new java.awt.Color(240, 240, 240));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "TimeStamp", "Produk ", "Jumlah ", "Total Harga", "Tunai Masuk", "Kembalian"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(riwayatLB)
                .addGap(151, 151, 151))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(riwayatLB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jpanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void namaTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaTFActionPerformed

    private void stokTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stokTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stokTFActionPerformed

    private void tambahBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahBTActionPerformed
        if (namaTF.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nama barang belum di input");
        } else if (hargaTF.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Harga barang belum di input");
        } else if(stokTF.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Stok barang belum di input");
        } else {
            ControllerDB.insertDB(namaTF.getText(), Long.valueOf(hargaTF.getText()), Integer.valueOf(stokTF.getText()));
            JOptionPane.showMessageDialog(null, "Barang berhasil diinput, refresh tabel!");
            updateTableProduk();
            clear();
        }
    }//GEN-LAST:event_tambahBTActionPerformed

    private void clearBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBTActionPerformed
        clear();
    }//GEN-LAST:event_clearBTActionPerformed

    private void editBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBTActionPerformed
          try {
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            int rowSelect = jTable1.getSelectedRow();

            if ("Edit".equals(editBT.getText())) {
                tambahBT.setEnabled(false);
                deleteBT.setEnabled(false);
                editBT.setText("Update");
                namaTF.setText(model.getValueAt(rowSelect, 1).toString());
                hargaTF.setText(model.getValueAt(rowSelect, 2).toString());
                stokTF.setText(model.getValueAt(rowSelect, 3).toString());
                namaTF.setEditable(false);
            } else {
                namaTF.setEditable(true);
                tambahBT.setEnabled(true);
                deleteBT.setEnabled(true);
                editBT.setText("Edit");
                ControllerDB.updateProdukDB(namaTF.getText(), Long.valueOf(hargaTF.getText()), Integer.parseInt(stokTF.getText()));
                updateTableProduk();
                clear();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Pilih produk sebelum mengedit!");
        }
    }//GEN-LAST:event_editBTActionPerformed

    private void hitungBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungBTActionPerformed
        String[] valueTotal = totalTF.getText().split(" ");
        String[] valueTunai = tunaiTF.getText().split(" ");
        try {
            Long longTotal = Long.valueOf(valueTotal[1]);
            Long longTunai = Long.valueOf(valueTunai[1]);
            kembaliTF.setText(String.format("Rp. %d", longTunai -  longTotal));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_hitungBTActionPerformed
    
    private void deleteBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBTActionPerformed
        try {
            ControllerDB.deletDB(selectName());
            updateTableProduk();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Pilih produk sebelum mengedit!");
        }
    }//GEN-LAST:event_deleteBTActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            int pengurangan =Integer.parseInt(jumlahTF.getText());
            int rowSelected = jTable1.getSelectedRow();
            String valueHarga = model.getValueAt(rowSelected, 2).toString();
            String valueProduk = model.getValueAt(rowSelected, 1).toString();
            updateTotalHarga(valueProduk, valueHarga);
    }//GEN-LAST:event_jTable1MouseClicked

    private void totalTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalTFActionPerformed

    private void jLabel2ComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jLabel2ComponentMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2ComponentMoved

    private void jLabel3ComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jLabel3ComponentMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3ComponentMoved

    private void tunaiTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tunaiTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tunaiTFActionPerformed

    private void produkTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_produkTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_produkTFActionPerformed

    private void jumlahTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlahTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jumlahTFActionPerformed

    private void bersihkanBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bersihkanBTActionPerformed
        produkTF.setText("");
        jumlahTF.setText("");
        tunaiTF.setText("");
        totalTF.setText("");
        kembaliTF.setText(""); 
    }//GEN-LAST:event_bersihkanBTActionPerformed

    private void simpanBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanBTActionPerformed
//        try {
            String[] valueTotal = totalTF.getText().split(" ");
            String[] valueTunai = tunaiTF.getText().split(" ");
            String[] valueKembali = kembaliTF.getText().split(" ");
            ControllerDB.insertHistory(produkTF.getText(), jumlahTF.getText(), valueTotal[1], valueTunai[1], valueKembali[1]);
            updateTableRiwayat() ;
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(null, "Lakukan Transaksi/Perhitungan Terlebih Dahulu!");
//        }
    }//GEN-LAST:event_simpanBTActionPerformed

    private void beliBUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beliBUTActionPerformed
        try {
            if(jumlahTF.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Masukkan Jumlah Barang yang Dibeli Terlebih Dahulu");
            } else {
                Produk produk = ControllerDB.getProdukbyNama(produkTF.getText());
                int pengurangan =Integer.parseInt(jumlahTF.getText());
                int newStok = (produk.getStock())-pengurangan;
                if (newStok>=1){
                    ControllerDB.updateStokDB(produkTF.getText(), newStok);
                    updateTableProduk();
                }else{
                    ControllerDB.deletDB(selectName());
                    updateTableProduk();
                }  
            }
        }catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Pilih produk sebelum mengedit!/Masukkan Jumlah Produk yang ingin Dibeli");
        }
        
    }//GEN-LAST:event_beliBUTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JumlahLB;
    private javax.swing.JButton beliBUT;
    private javax.swing.JButton bersihkanBT;
    private javax.swing.JButton clearBT;
    private javax.swing.JButton deleteBT;
    private javax.swing.JButton editBT;
    private javax.swing.JLabel hargaLB;
    private javax.swing.JTextField hargaTF;
    private javax.swing.JButton hitungBT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JPanel jpanel10;
    private javax.swing.JTextField jumlahTF;
    private javax.swing.JLabel kembaliLB;
    private javax.swing.JTextField kembaliTF;
    private javax.swing.JLabel namaLB;
    private javax.swing.JTextField namaTF;
    private javax.swing.JLabel produkLB;
    private javax.swing.JTextField produkTF;
    private javax.swing.JLabel riwayatLB;
    private javax.swing.JButton simpanBT;
    private javax.swing.JLabel stokLB;
    private javax.swing.JTextField stokTF;
    private javax.swing.JButton tambahBT;
    private javax.swing.JLabel totalLB;
    private javax.swing.JTextField totalTF;
    private javax.swing.JLabel tunaiLB;
    private javax.swing.JTextField tunaiTF;
    // End of variables declaration//GEN-END:variables
}
